import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type Repository = {
  id: number;
  name: string;
  full_name: string;
};

export type Time = {
  datetime: string;
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  /** Example 1:
   const res = await fetch("https://api.github.com/repos/vercel/next.js", {
    cache: "no-store",
  });

  change: <h1 className="text-3xl font-bold underline mb-4">{data.full_name}</h1>
 */

  /** Example 2:
  const res = await fetch(
    "http://worldtimeapi.org/api/timezone/America/New_York",
    {
      cache: "no-store",
    }
  );
 */

  /** Example 3:

  const res = await fetch(
    "http://worldtimeapi.org/api/timezone/America/New_York",
    {
      next: {
        revalidate: 5,
      },
    }
  );

  const data: Time = await res.json();

  add: <h1 className="text-3xl font-bold underline mb-4">{data.datetime}</h1>
  */

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-2 bg-gray-200 p-2 mb-6">
          <Link className="text-blue-500 underline" href="/">
            Home
          </Link>
          <Link className="text-red-500 underline" href="/posts">
            Posts
          </Link>
          <Link className="text-indigo-500 underline" href="/about">
            About
          </Link>
          <Link className="text-indigo-500 underline" href="/blog/123">
            Post 123
          </Link>
          <Link className="text-indigo-500 underline" href="/repo/next.js">
            Next.js
          </Link>
          <Link className="text-indigo-500 underline" href="/repo/turborepo">
            TurboRepo
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
